import { FaGamepad } from 'react-icons/fa';
import { CodeBracketIcon, DevicePhoneMobileIcon, GlobeAltIcon } from '@heroicons/react/24/solid';
import { LinkedInIcon } from '../../utils/icons';
import {
	ONCASE_URL,
	ONCASE_LINKEDIN_URL,
	INSPACE_URL,
	INSPACE_LINKEDIN_URL,
	EDUCANDUS_URL,
	EDUCANDUS_LINKEDIN_URL,
	ACASO_URL,
	ACASO_LINKEDIN_URL,
	NEUROTECH_URL,
	NEUROTECH_LINKEDIN_URL,
	JALAN_URL,
	JALAN_LINKEDIN_URL,
	GPC_GESTAO_URL,
	GPC_GESTAO_LINKEDIN_URL,
} from '../../constants/urls';
import {
	AIRFLOW,
	AWS,
	BASH,
	CI_CD,
	CONSTRUCT_3,
	CSS,
	DJANGO,
	DOCKER,
	FASTAPI,
	FLASK,
	GCP,
	GIT,
	GITHUB,
	GO,
	HTML,
	JAVASCRIPT,
	JUPYTER_NOTEBOOKS,
	KUBERNETES,
	LINUX,
	MONGODB,
	POSTGRESQL,
	POWERSHELL,
	PYTHON,
	REACT,
	REACT_NATIVE,
	REACT_REDUX,
	SQL,
	TAILWIND_CSS,
	TERRAFORM,
	TYPESCRIPT,
	VUE,
	WEBPACK,
} from '../../constants/skills';
import type { ActivityType } from '../../@types';

export const title: string = 'Work Experience';
export const subtitle: string = 'Allow me to show you my jobs with clients and in tech companies.';

export const experiences: ActivityType[] = [
	{
		title: 'Software Engineer | Full-time',
		subtitle: 'Neurotech. Apr 2024 - Present',
		description: [
			'In general, using skills in software, data engineering and backend development with Python, FastAPI, Terraform, Git, Airflow, Bash and cloud computing on AWS.',
			'Collaborate with cross-functional teams to achieve project goals.',
			'Ensure high-quality, scalable application development.',
			'Using AWS solutions such as Lambda, DynamoDB, EC2, Athena, S3, Step Functions and more.',
			'Extract data from different sources and make it available for many users in a data lake.',
		],
		skills: [
			AIRFLOW,
			AWS,
			BASH,
			CI_CD,
			DOCKER,
			FASTAPI,
			GCP,
			GIT,
			GITHUB,
			GO,
			JUPYTER_NOTEBOOKS,
			KUBERNETES,
			LINUX,
			POSTGRESQL,
			PYTHON,
			SQL,
			TERRAFORM,
		],
		links: [
			{ Icon: GlobeAltIcon, label: 'Website', url: NEUROTECH_URL },
			{ Icon: LinkedInIcon, label: 'LinkedIn', url: NEUROTECH_LINKEDIN_URL },
		],
		Icon: { Element: CodeBracketIcon, background: 'bg-indigo-600' },
	},
	{
		title: 'Software Engineer | Full-time',
		subtitle: 'Jalan. Apr 2024 - May 2024',
		description:
			'Worked as a Full Stack developer using Vue.js and Quasar along with Python and Lambda Functions (AWS).',
		skills: [AWS, BASH, GIT, POWERSHELL, PYTHON, VUE],
		links: [
			{ Icon: GlobeAltIcon, label: 'Website', url: JALAN_URL },
			{ Icon: LinkedInIcon, label: 'LinkedIn', url: JALAN_LINKEDIN_URL },
		],
		Icon: { Element: CodeBracketIcon, background: 'bg-indigo-600' },
	},
	{
		title: 'Software Engineer | Full-time',
		subtitle: 'Oncase. Feb 2022 - Dec 2023 (Feb 2022 - Aug 2022 as an intern)',
		description: [
			'In general, utilized skills in web development (Flask, Django, React and HTML/CSS), data engineering, CI/CD, Docker, GitHub Actions, and cloud computing (AWS and GCP).',
			'Developed Big Data applications with a focus on high efficiency, scalability, and low cost.',
			'Developed frontend applications using React (JavaScript, TypeScript and HTML/CSS) and Redux.',
			'Implemented backend functionality using Python frameworks Flask and Django.',
			'Implemented effective CI/CD pipelines for seamless integration and deployment through Docker and GitHub Actions.',
			'Collaborated with cross-functional teams to achieve project goals.',
			'Enhanced customer relationships through the delivery of top-notch solutions.',
			'Ensured high-quality and scalable application development.',
			'Hosted applications on Google Cloud Platform using Cloud Run and Artifact Registry.',
			'Utilized Amazon Web Services for hosting, leveraging services like Amplify, Route53, and Lambda.',
		],
		skills: [
			AIRFLOW,
			AWS,
			BASH,
			CI_CD,
			CSS,
			DJANGO,
			DOCKER,
			FLASK,
			GCP,
			GIT,
			GITHUB,
			HTML,
			JAVASCRIPT,
			LINUX,
			MONGODB,
			POSTGRESQL,
			PYTHON,
			REACT,
			REACT_REDUX,
			SQL,
			TAILWIND_CSS,
			TYPESCRIPT,
			WEBPACK,
		],
		links: [
			{ Icon: GlobeAltIcon, label: 'Website', url: ONCASE_URL },
			{ Icon: LinkedInIcon, label: 'LinkedIn', url: ONCASE_LINKEDIN_URL },
		],
		Icon: { Element: CodeBracketIcon, background: 'bg-indigo-600' },
	},

	{
		title: 'Game Developer | Internship',
		subtitle: 'Educandus. May 2020 - Dec 2020 and Jun 2021 - Oct 2021',
		description:
			'I have worked as a game developer using Construct 3 software and JavaScript, building educational games for students from preschool to high school levels.',
		skills: [CONSTRUCT_3, CSS, HTML, JAVASCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Website', url: EDUCANDUS_URL },
			{ Icon: LinkedInIcon, label: 'LinkedIn', url: EDUCANDUS_LINKEDIN_URL },
		],
		Icon: { Element: FaGamepad, background: 'bg-indigo-600' },
	},
];

export const freelances: ActivityType[] = [
	{
		title: 'Full Stack Developer',
		subtitle: 'GPC Gestão. Sep 2024 - Oct 2024',
		description: 'Built an admin website using React with TypeScript and Tailwind CSS.',
		skills: [CI_CD, GIT, GITHUB, REACT, TAILWIND_CSS, TYPESCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Website', url: GPC_GESTAO_URL },
			{ Icon: LinkedInIcon, label: 'LinkedIn', url: GPC_GESTAO_LINKEDIN_URL },
		],
		Icon: { Element: CodeBracketIcon, background: 'bg-indigo-600' },
	},
	{
		title: 'Mobile Engineer',
		subtitle: 'aca.so. Mar 2024',
		description: 'Worked as a Mobile Engineer in a freelance project (aca.so mobile app) using React Native.',
		skills: [GIT, GITHUB, REACT_NATIVE, TYPESCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Website', url: ACASO_URL },
			{ Icon: LinkedInIcon, label: 'LinkedIn', url: ACASO_LINKEDIN_URL },
		],
		Icon: { Element: DevicePhoneMobileIcon, background: 'bg-indigo-600' },
	},
	{
		title: 'Mobile Engineer',
		subtitle: 'InSpace. Aug 2022 - Oct 2022',
		description:
			'I have worked with the identification of objects (censored specificity) from a mobile camera for legal purposes.',
		skills: [GIT, GITHUB, REACT_NATIVE, REACT_REDUX, TYPESCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Website', url: INSPACE_URL },
			{ Icon: LinkedInIcon, label: 'LinkedIn', url: INSPACE_LINKEDIN_URL },
		],
		Icon: { Element: DevicePhoneMobileIcon, background: 'bg-indigo-600' },
	},
];
