import { CodeBracketIcon, DevicePhoneMobileIcon, GlobeAltIcon } from '@heroicons/react/24/solid';
import { FaGamepad } from 'react-icons/fa';
import {
	AIRFLOW,
	AWS,
	BASH,
	CI_CD,
	CONSTRUCT_3,
	CSS,
	DJANGO,
	DOCKER,
	FASTAPI,
	FLASK,
	GCP,
	GIT,
	GITHUB,
	GO,
	GRAFANA,
	HTML,
	JAVASCRIPT,
	JUPYTER_NOTEBOOKS,
	KUBERNETES,
	LINUX,
	MONGODB,
	POSTGRESQL,
	POWERSHELL,
	PYTHON,
	REACT,
	REACT_NATIVE,
	REACT_REDUX,
	SQL,
	TAILWIND_CSS,
	TERRAFORM,
	TYPESCRIPT,
	VUE,
} from '../../constants/skills';
import {
	ACASO_LINKEDIN_URL,
	ACASO_URL,
	EDUCANDUS_LINKEDIN_URL,
	EDUCANDUS_URL,
	GPC_GESTAO_LINKEDIN_URL,
	GPC_GESTAO_URL,
	INSPACE_LINKEDIN_URL,
	INSPACE_URL,
	JALAN_LINKEDIN_URL,
	JALAN_URL,
	NEUROTECH_LINKEDIN_URL,
	NEUROTECH_URL,
	ONCASE_LINKEDIN_URL,
	ONCASE_URL,
} from '../../constants/urls';
import { LinkedInIcon } from '../../utils/icons';
import type { ActivityType } from '../../types';

export const title: string = 'Work Experience';
export const subtitle: string = 'Allow me to show you my jobs with clients and in tech companies.';

export const experiences: ActivityType[] = [
	{
		title: 'Software Engineer | Full-time',
		subtitle: 'Neurotech. Apr 2024 - Present',
		location: 'Recife, Pernambuco, Brazil · Hybrid',
		description: [
			'In general, using skills in data engineering and backend development with Python, FastAPI, Go, Terraform, CI/CD, Docker, Git, Airflow, Bash, and cloud computing on AWS and GCP.',
			'Collaborate with cross-functional teams to achieve project goals.',
			'Ensure high-quality, scalable application development.',
			'Implementing backend functionality using Python, FastAPI and Go.',
			'Using AWS solutions such as Lambda, DynamoDB, EC2, Athena, S3, Step Functions and more.',
			'Working extracting data from different sources (internet, AWS S3, etc) and make it available in a data lake.',
			'Automating ETL pipelines with Apache Airflow.',
			'Using Grafana to visualise data and logs.',
		],
		skills: [
			AIRFLOW,
			AWS,
			BASH,
			CI_CD,
			DOCKER,
			FASTAPI,
			GCP,
			GIT,
			GITHUB,
			GO,
			GRAFANA,
			JUPYTER_NOTEBOOKS,
			KUBERNETES,
			LINUX,
			POSTGRESQL,
			PYTHON,
			SQL,
			TERRAFORM,
		],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: NEUROTECH_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: NEUROTECH_LINKEDIN_URL },
		],
		Icon: { Element: CodeBracketIcon, background: 'bg-indigo-600' },
	},
	{
		title: 'Full Stack Developer | Full-time',
		subtitle: 'Jalan. Apr 2024 - May 2024',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description: 'Worked in web apps using Vue.js and Quasar along with Python and AWS Lambda Functions.',
		skills: [AWS, BASH, GIT, POWERSHELL, PYTHON, VUE],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: JALAN_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: JALAN_LINKEDIN_URL },
		],
		Icon: { Element: CodeBracketIcon, background: 'bg-indigo-600' },
	},
	{
		title: 'Software Engineer | Full-time',
		subtitle: 'Oncase. Feb 2022 - Dec 2023 (Feb 2022 - Aug 2022 as an intern)',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description: [
			'In general, utilized skills in web development (Flask, Django, React and HTML/CSS), data engineering, CI/CD, Docker, GitHub Actions, and cloud computing (AWS and GCP).',
			'Developed Big Data applications with a focus on high efficiency, scalability, and low cost.',
			'Developed frontend applications using React, React Redux and TypeScript.',
			'Implemented backend functionality using Python frameworks Flask and Django.',
			'Implemented effective CI/CD pipelines for seamless integration and deployment through Docker and GitHub Actions.',
			'Collaborated with cross-functional teams to achieve project goals.',
			'Enhanced customer relationships through the delivery of top-notch solutions.',
			'Ensured high-quality and scalable application development.',
			'Hosted applications on Google Cloud Platform using Cloud Run and Artifact Registry.',
			'Automated ETL pipelines with Apache Airflow.',
			'Utilized Amazon Web Services for hosting, leveraging services like Amplify, Route53, and Lambda.',
		],
		skills: [
			AIRFLOW,
			AWS,
			BASH,
			CI_CD,
			CSS,
			DJANGO,
			DOCKER,
			FLASK,
			GCP,
			GIT,
			GITHUB,
			HTML,
			JAVASCRIPT,
			LINUX,
			MONGODB,
			POSTGRESQL,
			PYTHON,
			REACT,
			REACT_REDUX,
			SQL,
			TAILWIND_CSS,
			TYPESCRIPT,
		],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: ONCASE_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: ONCASE_LINKEDIN_URL },
		],
		Icon: { Element: CodeBracketIcon, background: 'bg-indigo-600' },
	},
	{
		title: 'Game Developer | Internship',
		subtitle: 'Educandus. May 2020 - Dec 2020 and Jun 2021 - Oct 2021',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description:
			'I have worked as a game developer using Construct 3 software and JavaScript, building educational games for students from preschool to high school levels.',
		skills: [CONSTRUCT_3, CSS, HTML, JAVASCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: EDUCANDUS_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: EDUCANDUS_LINKEDIN_URL },
		],
		Icon: { Element: FaGamepad, background: 'bg-indigo-600' },
	},
];

export const freelances: ActivityType[] = [
	{
		title: 'Full Stack Developer',
		subtitle: 'GPC Gestão. Sep 2024 - Oct 2024',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description:
			'Built an admin website for viewing, managing and downloading water consumption documents in multiple homes.',
		skills: [CI_CD, GIT, GITHUB, REACT, TAILWIND_CSS, TYPESCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: GPC_GESTAO_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: GPC_GESTAO_LINKEDIN_URL },
		],
		Icon: { Element: CodeBracketIcon, background: 'bg-indigo-600' },
	},
	{
		title: 'Mobile Engineer',
		subtitle: 'aca.so. Mar 2024',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description: 'Worked in a project (aca.so mobile app) using React Native, React Redux and TypeScript.',
		skills: [GIT, GITHUB, REACT_NATIVE, REACT_REDUX, TYPESCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: ACASO_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: ACASO_LINKEDIN_URL },
		],
		Icon: { Element: DevicePhoneMobileIcon, background: 'bg-indigo-600' },
	},
	{
		title: 'Mobile Engineer',
		subtitle: 'InSpace. Aug 2022 - Oct 2022',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description: 'Worked with the identification of certain objects from a mobile camera for legal purposes.',
		skills: [GIT, GITHUB, REACT_NATIVE, REACT_REDUX, TYPESCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: INSPACE_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: INSPACE_LINKEDIN_URL },
		],
		Icon: { Element: DevicePhoneMobileIcon, background: 'bg-indigo-600' },
	},
];
