import {
	AIRFLOW,
	AWS,
	BASH,
	BITBUCKET,
	CI_CD,
	CONSTRUCT_3,
	CSS,
	DJANGO,
	DOCKER,
	ELASTICSEARCH,
	FASTAPI,
	FLASK,
	GCP,
	GIT,
	GITHUB,
	GO,
	GRAFANA,
	GRAPHQL,
	HTML,
	JAVA,
	JAVASCRIPT,
	JIRA,
	KUBERNETES,
	LINUX,
	METABASE,
	MONGODB,
	MY_SQL,
	NEXT_JS,
	NODE,
	POSTGRESQL,
	POWERSHELL,
	PYTHON,
	REACT,
	REACT_NATIVE,
	REACT_REDUX,
	RPA,
	SENTRY,
	SQL,
	TAILWIND_CSS,
	TERRAFORM,
	TYPESCRIPT,
	VUE,
} from '@/constants/skills';
import {
	ACASO_LINKEDIN_URL,
	ACASO_URL,
	B3_LINKEDIN_URL,
	B3_URL,
	EDUCANDUS_LINKEDIN_URL,
	EDUCANDUS_URL,
	GPC_GESTAO_LINKEDIN_URL,
	GPC_GESTAO_URL,
	INSPACE_LINKEDIN_URL,
	INSPACE_URL,
	JALAN_LINKEDIN_URL,
	JALAN_URL,
	NEUROTECH_LINKEDIN_URL,
	NEUROTECH_URL,
	ONCASE_LINKEDIN_URL,
	ONCASE_URL,
	SANDBOX_LINKEDIN_URL,
	SANDBOX_URL,
	THOUGHTFUL_LINKEDIN_URL,
	THOUGHTFUL_URL,
} from '@/constants/urls';
import { LinkedInIcon } from '@/utils/icons';
import { CodeBracketIcon, DevicePhoneMobileIcon, GlobeAltIcon } from '@heroicons/react/24/solid';
import { FaGamepad } from 'react-icons/fa';
import type { ActivityType } from '@/types';

export const title: string = 'Work Experience';
export const subtitle: string = 'Allow me to show you my jobs with clients and in tech companies.';

const getIcon = (type: 'GAME' | 'MOBILE' | 'SOFTWARE' = 'SOFTWARE'): ActivityType['Icon'] => {
	switch (type) {
		case 'GAME':
			return { Element: FaGamepad, background: 'bg-indigo-600' };
		case 'MOBILE':
			return { Element: DevicePhoneMobileIcon, background: 'bg-blue-600' };
		default:
			return { Element: CodeBracketIcon, background: 'bg-teal-600' };
	}
};

export const experiences: ActivityType[] = [
	{
		title: 'Software Engineer | Full-time',
		subtitle: 'Sandbox Group. September 2025 - Present',
		location: 'London Area, United Kingdom · Remote',
		description: [
			'Working at the Kids & Family vertical for PlayKids App and SVOD integration.',
			'Implementing backend features with Python, FastAPI, Flask and Go on AWS and GCP, with infrastructure as code in Terraform and Kubernetes.',
			'Developing frontend features with Next.js and React.',
		],
		skills: [
			AWS,
			BASH,
			CI_CD,
			DOCKER,
			ELASTICSEARCH,
			FASTAPI,
			FLASK,
			GCP,
			GIT,
			GITHUB,
			GO,
			GRAPHQL,
			JAVA,
			JIRA,
			KUBERNETES,
			METABASE,
			MONGODB,
			MY_SQL,
			NEXT_JS,
			NODE,
			POSTGRESQL,
			PYTHON,
			REACT,
			SENTRY,
			TAILWIND_CSS,
			TERRAFORM,
			TYPESCRIPT,
		],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: SANDBOX_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: SANDBOX_LINKEDIN_URL },
		],
		Icon: getIcon(),
	},
	{
		title: 'Forward Deployed Engineer | Contract',
		subtitle: 'Thoughtful AI. August 2025 - April 2026',
		location: 'Austin, Texas, United States · Remote',
		description: [
			'Implemented RPA in Python to automate RCM processes for healthcare companies in the United States.',
			'Built internal libraries and tools for other engineers.',
		],
		skills: [AWS, BASH, BITBUCKET, CI_CD, FASTAPI, GIT, GITHUB, JIRA, PYTHON, RPA, TERRAFORM],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: THOUGHTFUL_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: THOUGHTFUL_LINKEDIN_URL },
		],
		Icon: getIcon(),
	},
	{
		title: 'Software Engineer | Full-time',
		subtitle: 'B3. April 2024 - August 2025',
		location: 'Recife, Pernambuco, Brazil · Hybrid',
		description: [
			'Worked at Neurotech (Trillia), acquired by B3.',
			'Data engineering and backend development with Python, FastAPI and Go: extracted data from sources such as the internet and AWS S3 into a data lake, automated ETL pipelines with Airflow and monitored them in Grafana.',
			'Ran workloads on AWS (Lambda, DynamoDB, EC2, Athena, S3, Step Functions) and GCP with Terraform, Docker, CI/CD and Bash.',
		],
		skills: [
			AIRFLOW,
			AWS,
			BASH,
			CI_CD,
			DOCKER,
			ELASTICSEARCH,
			FASTAPI,
			GCP,
			GIT,
			GITHUB,
			GO,
			GRAFANA,
			JIRA,
			KUBERNETES,
			LINUX,
			POSTGRESQL,
			PYTHON,
			RPA,
			SQL,
			TERRAFORM,
		],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: B3_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: B3_LINKEDIN_URL },
			{ Icon: GlobeAltIcon, label: 'Neurotech Website', url: NEUROTECH_URL },
			{ Icon: LinkedInIcon, label: "Neurotech's LinkedIn", url: NEUROTECH_LINKEDIN_URL },
		],
		Icon: getIcon(),
	},
	{
		title: 'Full Stack Developer | Full-time',
		subtitle: 'Jalan. April 2024 - May 2024',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description: 'Worked in web apps using Vue.js and Quasar along with Python and AWS Lambda Functions.',
		skills: [AWS, BASH, GIT, JIRA, POWERSHELL, PYTHON, VUE],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: JALAN_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: JALAN_LINKEDIN_URL },
		],
		Icon: getIcon(),
	},
	{
		title: 'Software Engineer | Full-time',
		subtitle: 'Oncase. August 2022 - December 2023',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description: [
			'Developed Big Data applications with a focus on high efficiency, scalability and low cost.',
			'Implemented backends with Flask and Django and frontends with React, React Redux and TypeScript.',
			'Automated ETL pipelines with Apache Airflow and CI/CD pipelines with Docker and GitHub Actions.',
			'Hosted applications on GCP (Cloud Run, Artifact Registry) and AWS (Amplify, Route53, Lambda).',
		],
		skills: [
			AIRFLOW,
			AWS,
			BASH,
			CI_CD,
			CSS,
			DJANGO,
			DOCKER,
			FLASK,
			GCP,
			GIT,
			GITHUB,
			HTML,
			JAVASCRIPT,
			JIRA,
			LINUX,
			METABASE,
			MONGODB,
			POSTGRESQL,
			PYTHON,
			REACT,
			REACT_REDUX,
			SQL,
			TAILWIND_CSS,
			TYPESCRIPT,
		],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: ONCASE_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: ONCASE_LINKEDIN_URL },
		],
		Icon: getIcon(),
	},
];

export const internships: ActivityType[] = [
	{
		title: 'Full Stack Developer',
		subtitle: 'Oncase. February 2022 - August 2022',
		location: 'Recife, Pernambuco, Brazil · Remote',
		skills: [
			AWS,
			BASH,
			CSS,
			FLASK,
			GIT,
			GITHUB,
			HTML,
			JAVASCRIPT,
			JIRA,
			LINUX,
			METABASE,
			MONGODB,
			PYTHON,
			REACT,
			REACT_REDUX,
		],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: ONCASE_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: ONCASE_LINKEDIN_URL },
		],
		Icon: getIcon(),
	},
	{
		title: 'Game Developer',
		subtitle: 'Educandus. May 2020 - December 2020 and June 2021 - October 2021',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description: 'Built educational games for preschool to high school students with Construct 3 and JavaScript.',
		skills: [CONSTRUCT_3, CSS, HTML, JAVASCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: EDUCANDUS_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: EDUCANDUS_LINKEDIN_URL },
		],
		Icon: getIcon('GAME'),
	},
];

export const freelances: ActivityType[] = [
	{
		title: 'Full Stack Developer',
		subtitle: 'GPC Gestão. September 2024 - October 2024',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description:
			'Admin website for viewing, managing and downloading water consumption documents across multiple homes.',
		skills: [CI_CD, GIT, GITHUB, REACT, TAILWIND_CSS, TYPESCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: GPC_GESTAO_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: GPC_GESTAO_LINKEDIN_URL },
		],
		Icon: getIcon(),
	},
	{
		title: 'Mobile Developer',
		subtitle: 'aca.so. March 2024',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description: 'Worked on the aca.so mobile app with React Native, React Redux and TypeScript.',
		skills: [GIT, GITHUB, REACT_NATIVE, REACT_REDUX, TYPESCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: ACASO_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: ACASO_LINKEDIN_URL },
		],
		Icon: getIcon('MOBILE'),
	},
	{
		title: 'Mobile Developer',
		subtitle: 'InSpace. August 2022 - October 2022',
		location: 'Recife, Pernambuco, Brazil · Remote',
		description: 'Worked with the identification of certain objects from a mobile camera for legal purposes.',
		skills: [GIT, GITHUB, REACT_NATIVE, REACT_REDUX, TYPESCRIPT],
		links: [
			{ Icon: GlobeAltIcon, label: 'Company Website', url: INSPACE_URL },
			{ Icon: LinkedInIcon, label: "Company's LinkedIn", url: INSPACE_LINKEDIN_URL },
		],
		Icon: getIcon('MOBILE'),
	},
];
